%-Configfile for preprocessfmri.m
%__________________________________________________________________________


%-Please specify parallel or nonparallel
%-e.g. for preprocessing and individualstats, set to 1 (parallel)
%-for groupstats, set to 0 (nonparallel)
paralist.parallel = '1';

% fMRI parameters
%-spm batch templates location
paralist.batchtemplatepath = '/scsnlscripts/brainImaging/mri/fmri/preprocessing/spm12/preprocessfmrimodules/batchtemplates/'; %'/oak/stanford/groups/menon/scsnlscripts_vsochat/fmri/spm/spm8/preprocessing/preprocessfmrimodules/batchtemplates/';
%-SPM version
paralist.spmversion = 'spm12'; 


%-Subject list
paralist.subjectlist =  '/projects/yunjip/2024_md_td_tutoring/data/subjectlist/indivstats_subjectlist_comparison_dot.csv';


%-Run list
paralist.runlist = '/projects/yunjip/2024_md_td_tutoring/data/subjectlist/comparison_dot.txt';


% Please specify the data type of preprocessed images
% 'nii' for Nifti 4-D format, 'img' for Analyze 7.5 format
% If you would like the script to decide which type to use, uncomment the 
% second line and comment the first line
paralist.data_type = 'nii';
% paralist.data_type = [''];

% Please indicate whether to use head movements (1:Yes; 0:No)
paralist.include_mvmnt = 1;

%-Please specify the standard preprocessing pipeline you have used
paralist.pipeline = 'swgcar';


% -------------------------------------------------------------------------
% I/O parameters
% - Project directory - output of the individualstats will be saved in the
% results/taskfmri folder of the project directory

paralist.projectdir = '/projects/yunjip/2024_md_td_tutoring';
paralist.taskdsgndir = '/projects/yunjip/2024_md_td_tutoring';

% Please specify the folder containing preprocessed data 
paralist.preprocessed_folder    = 'swgcar_spm12_pediatric';

% Please specify the folder in which to put the statistics results (below 'stats_spm' 
% which is generated by default)
% If you include_volrepair = 1 below, set stats_folder = 'temp_stats';
paralist.stats_folder = 'stats_spm12_swgcar_pediatric_comp_dot';


% task and contrast parameters
%-Please specify the task design file (*.m)
%-If task design *.mat file already exists, please specify as a mat file (e.g., task_design.mat)

%paralist.task_dsgn  = 'task_design_comparison_dot.mat';
paralist.task_dsgn  = 'task_design_comparison_dot.mat';


%-Please specify the file holding contrasts
paralist.contrastmat    = 'contrasts.mat';
% paralist.contrastmat = ['']; 

%-Please specify the TR otherwise the default is 2.0 s
paralist.TR = 2.0;

%-Please specify the type of serial correlations
%-other options are 'none', 'FAST'
paralist.cvi = 'AR(1)';

%-please specify the whole brain mask
paralist.whole_brain_mask =[''];


% Please indicate whether it is based on VolRepair pipeline
% 1: use volrepair pipeline data for individual stats
% 0: use standard pipeline data
% If you set volrepair = 1, set up VolRepair section below
% If you set volrepair = 0, do not set up VolRepair section below 
paralist.include_volrepair = 0;

% -------------------------------------------------------------------------
% VolRepair Preprocessing Setup
% -------------------------------------------------------------------------

% Please specify the volrepair preprocessing pipeline
paralist.volpipeline = 'swgcar';

% Please specify the volrepair preprocessed folder
paralist.volrepaired_folder = 'volrepair_spm12';

% Please specify the folder for VolRepaired data (swavrI*)
% the stats folder is under 'stats_spm8' folder (generated by default)
paralist.repaired_stats   = 'stats_spm12_VolRepair';

